name: dockerPipenv

on: [push]

jobs:
  DockerComposePytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker Build
      run: docker-compose build
    - name: Docker Compose Up
      run: docker-compose up -d
    - name: Pipenv Run Pytest
      run: docker-compose exec -T flask_app pipenv run test
    - name: Pipenv Run Lint
      run: docker-compose exec -T flask_app pipenv run lint
