name: Rspec for Rails with PostgreSQL
on: push
jobs:
  # Label of the container job
  rspec:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    services: # サービスコンテナの定義
      postgres:
        image: postgres:15.0-alpine3.16
        ports:
            - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >- # 起動後のヘルスチェック
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - actions/setup-ruby@v1
        with:
            ruby-version: 3.1
      - name: Rspec
        env: 
          # テスト対象の Rails アプリケーションは次の環境変数で DB 接続先を設定できる想定
          - DB_HOST: localhost
          - DB_PORT: 5432
        run: |
            bundle install
            bundle install --jobs 4 --retry 3
            bundle exec rails db:create
            bundle exec rails db:migrate
            bundle exec rspec
